<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="EtherCATDeviceBase" Id="{dc0e21cf-0051-4f40-b2a9-8775d4f4e84c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EtherCATDeviceBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	WcState AT%I* : BOOL;
	InputToggle AT%I* : BOOL;
	State AT%i* : UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EtherCATDeviceBase">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>