<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="EtherNetIPMaster" Id="{23d346be-69ba-4116-9848-11de21f5338e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EtherNetIPMaster
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	DevState AT%i* : UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EtherNetIPMaster">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>