///////////////////////////////////////////////////////////////////////////////
// CppDevProjectInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "CppDevProjectServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
