///////////////////////////////////////////////////////////////////////////////
// CppDevProjectServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_CppDevProject = 0x3F000000;
#define SRVNAME_CPPDEVPROJECT "CppDevProject"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_CppDevProjectCModule1 = {0x2871042b,0x22f5,0xb544,{0xdb,0xba,0xf9,0xaf,0x3e,0x6c,0x99,0xdd}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Parameter = 0x00000001;
const PTCID PID_Module1Counter = 0x00000002;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Module1Parameter, *PModule1Parameter;

typedef struct _Module1Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} Module1Outputs, *PModule1Outputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
