///////////////////////////////////////////////////////////////////////////////
// Module1.h
#pragma once

#include "CppDevProjectInterfaces.h"

class CModule1 
	: public ITComObject
///<AutoGeneratedContent id="InheritanceList">
	, public ITComOnlineChange
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()

	CModule1();
	virtual	~CModule1();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITComOnlineChange
	virtual HRESULT TCOMAPI PrepareOnlineChange(ITComObject* ipOldObj, TmcInstData* pOldInfo);
	virtual HRESULT TCOMAPI PerformOnlineChange(ITComObject* ipOldObj, TmcInstData* pOldInfo);

	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	Module1Parameter m_Parameter;
	ULONG m_Counter;
	Module1Inputs* m_pInputs;
	Module1Outputs* m_pOutputs;
///</AutoGeneratedContent>

	ITcADIPtr m_spADI;

	// TODO: Custom variable
};
