<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN_1" Id="{94a3cf28-c82f-432b-98ee-a1011d16688e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_1
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_1">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>