<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_ThirdObject" Id="{cf740e6b-86ed-48db-b106-663968cd5241}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ThirdObject
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_parentObject : ITF_Object;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{f32fca7e-b31d-43a0-ad58-d0162a78c803}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	ParentObject : ITF_Object;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_parentObject := ParentObject;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ThirdObject">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ThirdObject.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>