<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{902d5820-3fe0-4aff-8c96-1938b68e5f95}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	test : EventLoggerClass;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[test();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>