<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SocketRecieveTask" Id="{4c37506a-f01e-46ef-8308-65996d9f9557}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SocketRecieveTask
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SocketRecieveTask">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>