<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SocketCloseTask" Id="{a9ec101e-14e7-48c3-bce3-b5c9494e4a85}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SocketCloseTask
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SocketCloseTask">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>